/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'monitorStatus': MotiaStream<{ monitorId: string; timestamp: string; latency?: number; statusCode?: number; success?: boolean }>
  }

  interface Handlers {
    'SendAlert': EventHandler<{ monitorId: string; severity: 'NORMAL' | 'WARNING' | 'CRITICAL'; diagnostic?: unknown }, never>
    'PingMonitor': EventHandler<{ monitorId: string }, { topic: 'CHECK_ANOMALY'; data: { monitorId: string } } | { topic: 'MONITOR_DOWN'; data: { monitorId: string } }>
    'MonitorDown': EventHandler<{ monitorId: string }, { topic: 'SEND_ALERT'; data: { monitorId: string; severity: 'NORMAL' | 'WARNING' | 'CRITICAL'; diagnostic?: unknown } }>
    'CheckAnomaly': EventHandler<{ monitorId: string }, { topic: 'SEND_ALERT'; data: { monitorId: string; severity: 'NORMAL' | 'WARNING' | 'CRITICAL'; diagnostic?: unknown } }>
    'PingMonitorsCron': CronHandler<{ topic: 'PING_MONITOR'; data: { monitorId: string } }>
    'MonitorStatusSSE': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CreateMonitorAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<201, { monitorId: string }>, never>
  }
    
}